name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      FEED_ITEMS_ID: ${{ secrets.FEED_ITEMS_ID }}
      FEED_ITEMS_PREVIEW_ID: ${{ secrets.FEED_ITEMS_PREVIEW_ID }}
      MSTDN_URL: "https://mastodon.social"
    name: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn generate-wrangler
      - run: yarn test